title: "My GitHub Blog"
description: "문쫑의 깃헙 블로그입니다"
baseurl: ""
url: "https://stradivirus.github.io" # 여기에 실제 GitHub 사용자명을 넣으세요

# Jekyll 테마 설정
theme: minima
# remote_theme: pages-themes/minimal@v0.2.0 # 다른 테마를 원한다면 주석 해제

# Author 정보
author:
  name: "문성종"
  email: "stradivirus9@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# Collections (블로그 포스트용)
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Timezone
timezone: Asia/Seoul
